#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0
"""
gen_config_gz.py - turn config.template into a gzip-compressed C byte array.

Usage: gen_config_gz.py <input-template> <output-header>

Produces a small generated header (config_gz_data.h) containing the exact
gzip stream that /proc/config.gz would emit if it were serving the given
plaintext config, so shadow_configz.c can hand it straight to userspace with
simple_read_from_buffer() -- no runtime zlib dependency required (real
CONFIG_IKCONFIG builds do compress on the fly, but embedding the ready-made
stream keeps this module buildable regardless of whether the target kernel
enables CONFIG_ZLIB_DEFLATE).

Run automatically by the Makefile before compiling shadow_configz.c; not
part of the runtime kernel module itself.
"""
import gzip
import sys


def main() -> int:
    if len(sys.argv) != 3:
        print(f"usage: {sys.argv[0]} <input-template> <output-header>", file=sys.stderr)
        return 1

    src, dst = sys.argv[1], sys.argv[2]

    with open(src, "rb") as f:
        raw = f.read()

    # mtime=0 keeps the output byte-for-byte reproducible across builds.
    compressed = gzip.compress(raw, compresslevel=9, mtime=0)

    with open(dst, "w") as f:
        f.write("/* SPDX-License-Identifier: GPL-2.0 */\n")
        f.write("/* Auto-generated by gen_config_gz.py from config.template. DO NOT EDIT. */\n\n")
        f.write("static const unsigned char shadow_configz_gz[] = {\n")
        for i in range(0, len(compressed), 16):
            chunk = compressed[i:i + 16]
            f.write("\t" + ", ".join(f"0x{b:02x}" for b in chunk) + ",\n")
        f.write("};\n\n")
        f.write(f"static const unsigned int shadow_configz_gz_len = {len(compressed)}U;\n")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
