// SPDX-License-Identifier: GPL-2.0
/*
 * lkm4ctr/readme.txt.c - contents of diagfs/readme.txt as a C string.
 *
 * This mirrors helper.sh.c: the canonical text lives here as a plain C
 * string and is served read-only (mode 0444) at the root of the lkm4ctr
 * diagfs mount by lkm4ctr_diagfs.c (see LKM4CTR_DIAG_README). It exists so
 * that anyone who mounts the filesystem, without any prior documentation,
 * can `cat readme.txt` and learn the full tree layout and how to drive it,
 * without needing this repository's source tree at all.
 */
#include <linux/types.h>

const char lkm4ctr_readme_txt_data[] =
"lkm4ctr diagfs - readme\n"
"========================\n"
"\n"
"This is the \"lkm4ctr\" pseudo-filesystem exposed by the lkm4ctr.ko kernel\n"
"module. Mounting it gives you a read/write diagnostics and control tree\n"
"covering every subsystem linked into lkm4ctr.ko: shadow_hijack (the shared\n"
"hook engine), shadow_ns, shadow_sysvipc, shadow_mqueue and\n"
"shadow_cgdevices, plus module-wide load/unload/hot-reload control.\n"
"\n"
"This file is generated from the canonical diagfs documentation living in\n"
"lkm4ctr/readme.txt.c, and is kept in sync with lkm4ctr_diagfs.c by hand.\n"
"\n"
"Quick start\n"
"-----------\n"
"  # mount the filesystem somewhere (any empty directory)\n"
"  mkdir -p /mnt/lkm4ctr\n"
"  mount -t lkm4ctr diag /mnt/lkm4ctr\n"
"\n"
"  # inspect overall state\n"
"  cat /mnt/lkm4ctr/global/status\n"
"  cat /mnt/lkm4ctr/global/log\n"
"\n"
"  # or source the bundled shell helper for a friendlier interface\n"
"  export lkm4ctr_diagfs=/mnt/lkm4ctr\n"
"  . \"$lkm4ctr_diagfs/helper.sh\"\n"
"  lkm4ctr status\n"
"  lkm4ctr help\n"
"\n"
"See \"helper.sh\" below for the full command reference of that wrapper; it\n"
"is entirely optional -- every diagfs file can just as well be read with\n"
"cat/echo directly, which is what the wrapper itself does under the hood.\n"
"\n"
"Every \"control\" file accepts plain-text commands via a single write(2),\n"
"e.g. `echo unload > control`; every \"status\"/\"log\"/listing file is read\n"
"only (open + read, no special ioctl needed) and is regenerated fresh on\n"
"every open(), so repeated `cat`s always show live state.\n"
"\n"
"Root layout\n"
"-----------\n"
"  ./readme.txt                   - this file (0444, read-only).\n"
"  ./helper.sh                    - POSIX-sh helper script (0555,\n"
"                                    read+execute-only); see its own header\n"
"                                    comment or \"Shell helper\" below.\n"
"\n"
"  ./global/control                (0644) - read: command help. write:\n"
"    load                          load every submodule (alias: load_all)\n"
"    unload                        graceful whole-module self-unload\n"
"                                   (aliases: 1, remove, graceful)\n"
"    forceunload                   force whole-module self-unload\n"
"                                   (aliases: force, force_unload)\n"
"    force2                        start (or escalate an in-progress\n"
"                                   unload to) the aggressive force2\n"
"                                   sequence, which overrides\n"
"                                   module_refcount() bookkeeping directly\n"
"                                   to push an unload through even when\n"
"                                   references look stuck.\n"
"  ./global/status                 (0444) one of exactly: \"active\",\n"
"                                   \"loading\", \"graceful unloading\",\n"
"                                   \"force unloading\". \"unloaded\" is\n"
"                                   reserved for completeness but is not\n"
"                                   observable once this mount is reachable,\n"
"                                   because the module itself would already\n"
"                                   be gone by then.\n"
"  ./global/log                    (0444) every log line, unfiltered, from\n"
"                                   every subsystem.\n"
"  ./global/resources              (0444) best-effort aggregate of live\n"
"                                   resources already tracked by the\n"
"                                   namespace, POSIX mqueue, SysV IPC and\n"
"                                   hook registries.\n"
"  ./global/references             (0444) breaks module_refcount() down\n"
"                                   into diagfs mount count + in-flight\n"
"                                   shadow_hook calls + unaccounted \"other\"\n"
"                                   holders, to explain why rmmod is\n"
"                                   refusing to unload lkm4ctr.ko.\n"
"  ./global/hotreload/status       (0444) \"first load\" vs \"hot-reloaded\"\n"
"                                   boot kind, plus in-progress hot-reload\n"
"                                   state.\n"
"  ./global/hotreload/log          (0444) hot-reload subsystem's own log.\n"
"  ./global/hotreload/do-hot-reload\n"
"                                   (0200, write-only) write an absolute\n"
"                                   path to a replacement lkm4ctr.ko to\n"
"                                   trigger a hot reload: validate path ->\n"
"                                   quiesce hooks -> drain refcount ->\n"
"                                   unmount diagfs -> hand off to a\n"
"                                   detached \"rmmod && insmod <path>\n"
"                                   hotreload=1\" shell -> exit. Watch\n"
"                                   ./status and ./log in the same\n"
"                                   directory for progress.\n"
"\n"
"Per-submodule directories\n"
"-------------------------\n"
"Every submodule below (hijack, ns, sysvipc, mqueue, cgroupdevices) has at\n"
"least:\n"
"  <dir>/control    (0644) read: command help. write: load / unload\n"
"                   (aliases: 1, remove, graceful) / forceunload (aliases:\n"
"                   force, force_unload). force2 is a global-only\n"
"                   escalation and has no per-module meaning here.\n"
"  <dir>/status     (0444) that submodule's own lifecycle state.\n"
"  <dir>/log        (0444) that submodule's own log lines.\n"
"  <dir>/references (0444) that submodule's own contribution to\n"
"                   module_refcount(), broken down the same way\n"
"                   global/references is.\n"
"\n"
"  ./hijack/functions\n"
"    (0444) shadow_hijack is the shared hook engine every other\n"
"    submodule's hooks are installed through, so instead of its own\n"
"    hooks listing it has \"functions\": a live listing of every currently\n"
"    registered hook across all submodules. Ordering rule: since every\n"
"    other submodule depends on this shared engine, hijack's graceful\n"
"    unload is refused (-EBUSY) while any other submodule is still\n"
"    active; forceunload instead gracefully unloads every other active\n"
"    submodule first, waits briefly, force-unloads whatever remains\n"
"    active, then finally tears shadow_hijack itself down.\n"
"\n"
"  ./ns/hooks, ./ns/namespaces\n"
"    (0444 each) shadow_ns's own installed hooks, and a full live registry\n"
"    dump of every namespace object plus which task groups (tgids) belong\n"
"    to each.\n"
"  ./ns/<type>/{control,status,log,namespaces}\n"
"    one directory per shadow_ns namespace type: pid, ipc, mnt, net,\n"
"    user, uts, cgroup. shadow_ns still has one shared init()/exit() for\n"
"    the whole subsystem, so each per-type control/status file\n"
"    intentionally reflects that shared backing lifecycle rather than\n"
"    pretending individual types can be independently loaded/unloaded.\n"
"    Each per-type namespaces file is filtered to only that type's live\n"
"    namespace objects and member tgids.\n"
"\n"
"  ./sysvipc/hooks, ./sysvipc/resources\n"
"    (0444 each) shadow_sysvipc's own installed hooks, and a live listing\n"
"    of currently tracked SysV IPC objects (message queues, semaphores,\n"
"    shared memory segments).\n"
"\n"
"  ./mqueue/hooks, ./mqueue/msg\n"
"    (0444 each) shadow_mqueue's own installed hooks, and a live listing\n"
"    of the current in-memory POSIX message queue / message state.\n"
"\n"
"  ./cgroupdevices/hooks\n"
"    (0444) shadow_cgdevices's own installed hooks.\n"
"\n"
"Notes on design\n"
"---------------\n"
"* control vs status is a strict split everywhere: control is the write\n"
"  command surface (and, on read, a short command summary), status is a\n"
"  strict lifecycle-state readout (never a command summary).\n"
"* This is a small, fully in-memory pseudo-filesystem in the same spirit\n"
"  as ramfs/securityfs: the whole tree is built once at mount time; file\n"
"  contents are regenerated fresh on every open(), so state is always\n"
"  live, but the directory/file layout itself never changes after mount.\n"
"* Objects that cannot be enumerated as fixed dentries up front (e.g.\n"
"  currently queued mqueue messages, or live shadow_ns/SysV IPC objects\n"
"  that may come and go after mount) are exposed as readable listing\n"
"  files (namespaces, msg, resources, functions) rather than one dentry\n"
"  per live object.\n"
"* Everything under ./global and every per-submodule directory keeps\n"
"  working even if some submodules are currently unloaded; only that\n"
"  submodule's own control/status/log/references (and hooks/namespaces/\n"
"  msg/resources where applicable) reflect an \"unloaded\" state until it\n"
"  is loaded again via its control file (or global/control's \"load\").\n"
"\n"
"Shell helper (helper.sh)\n"
"------------------------\n"
"helper.sh is meant to be sourced, not executed:\n"
"  export lkm4ctr_diagfs=/path/to/mountpoint\n"
"  . \"$lkm4ctr_diagfs/helper.sh\"\n"
"\n"
"It then defines an `lkm4ctr` dispatcher function and matching standalone\n"
"functions:\n"
"  lkm4ctr mount                    mount -t lkm4ctr diag \"$lkm4ctr_diagfs\"\n"
"  lkm4ctr umount                   unmount \"$lkm4ctr_diagfs\"\n"
"  lkm4ctr status                   summarise global + every submodule's status\n"
"  lkm4ctr control <target> <cmd>   write <cmd> to <target>/control\n"
"  lkm4ctr load [target]            control <target|global> load\n"
"  lkm4ctr unload [target]          control <target|global> unload\n"
"  lkm4ctr forceunload [target]     control <target|global> forceunload\n"
"  lkm4ctr force2                   control global force2 (aggressive escalation)\n"
"  lkm4ctr logcat [target]          cat <target|global>/log (\"hotreload\" for the hot-reload log)\n"
"  lkm4ctr references [target]      cat <target|global>/references\n"
"  lkm4ctr hot-upgrade <path-to-ko> echo <path> > global/hotreload/do-hot-reload\n"
"  lkm4ctr help                     print this command summary\n"
"\n"
"<target> is one of: global, hijack, ns, sysvipc, mqueue, cgroupdevices.\n"
"$lkm4ctr_diagfs must be exported to the mountpoint before calling any of\n"
"these; every function checks for it and prints a clear error otherwise.\n"
"Run `sh helper.sh` directly (with no arguments) and it just prints this\n"
"same command summary and exits -- it is harmless, but sourcing it is the\n"
"intended usage.\n";

const unsigned long lkm4ctr_readme_txt_size = sizeof(lkm4ctr_readme_txt_data) - 1;
